# Generated by Django 4.0.4 on 2022-07-05 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boleta',
            fields=[
                ('idBoleta', models.AutoField(primary_key=True, serialize=False, verbose_name='Numero boleta')),
                ('precioTotal', models.IntegerField(verbose_name='Precio total')),
                ('fecha', models.DateField(verbose_name='Fecha boleta')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProduct',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id categoria')),
                ('nombreCategoria', models.CharField(max_length=40, unique=True, verbose_name='Nombre categoria')),
            ],
            options={
                'verbose_name_plural': 'CategoriaProduct',
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('IdCodigo', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Id Codigo')),
                ('Porcentaje', models.IntegerField(verbose_name='Porcentaje Descuento')),
            ],
        ),
        migrations.CreateModel(
            name='FormSolicitud',
            fields=[
                ('idSolicitud', models.AutoField(primary_key=True, serialize=False, verbose_name='Id solicitud')),
                ('nombreCompleto', models.CharField(max_length=60, verbose_name='Nombre completo')),
                ('mailSolicitante', models.CharField(max_length=60, verbose_name='Mail del solicitate')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name_plural': 'FormSolicitud',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nombre de usuario')),
                ('mail', models.CharField(max_length=60, unique=True, verbose_name='Correo')),
                ('password', models.CharField(max_length=60, verbose_name='Contraseña')),
                ('suscripcion', models.BooleanField(default=False, verbose_name='membresia')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='CatalogoProduct',
            fields=[
                ('idPlanta', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('nombrePlanta', models.CharField(max_length=30, unique=True, verbose_name='Nombre Producto')),
                ('descripcionPlanta', models.CharField(blank=True, max_length=500, verbose_name='Descripcion Producto')),
                ('precioPlanta', models.IntegerField(verbose_name='Precio Producto')),
                ('imagenPlanta', models.CharField(max_length=2000, verbose_name='url foto del Producto')),
                ('stockPlanta', models.IntegerField(verbose_name='Stock Producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriaproduct')),
            ],
            options={
                'verbose_name_plural': 'CatalogoProduct',
            },
        ),
    ]
