# Generated by Django 4.0.4 on 2022-07-13 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogoproduct',
            old_name='descripcionPlanta',
            new_name='descripcionProducto',
        ),
        migrations.RenameField(
            model_name='catalogoproduct',
            old_name='idPlanta',
            new_name='idProduct',
        ),
        migrations.RenameField(
            model_name='catalogoproduct',
            old_name='imagenPlanta',
            new_name='imagenProducto',
        ),
        migrations.RenameField(
            model_name='catalogoproduct',
            old_name='nombrePlanta',
            new_name='nombreProducto',
        ),
        migrations.RenameField(
            model_name='catalogoproduct',
            old_name='precioPlanta',
            new_name='precioProducto',
        ),
        migrations.RenameField(
            model_name='catalogoproduct',
            old_name='stockPlanta',
            new_name='stockProducto',
        ),
    ]
