# Generated by Django 4.0.4 on 2022-07-14 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_descripcionplanta_catalogoproduct_descripcionproducto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogoproduct',
            old_name='idProduct',
            new_name='idProducto',
        ),
    ]
