# Generated by Django 4.0.4 on 2022-07-14 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_idproduct_catalogoproduct_idproducto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogoproduct',
            old_name='descripcionProducto',
            new_name='descripcionPlanta',
        ),
        migrations.RenameField(
            model_name='catalogoproduct',
            old_name='idProducto',
            new_name='idPlanta',
        ),
        migrations.RenameField(
            model_name='catalogoproduct',
            old_name='imagenProducto',
            new_name='imagenPlanta',
        ),
        migrations.RenameField(
            model_name='catalogoproduct',
            old_name='nombreProducto',
            new_name='nombrePlanta',
        ),
        migrations.RenameField(
            model_name='catalogoproduct',
            old_name='precioProducto',
            new_name='precioPlanta',
        ),
        migrations.RenameField(
            model_name='catalogoproduct',
            old_name='stockProducto',
            new_name='stockPlanta',
        ),
    ]
